#pragma once

#define CONTROL_CODE_DEFAULT 0
#define CONTROL_CODE_CALL 1
#define CONTROL_CODE_CAUGHT 2
#define CONTROL_CODE_RETURN_TO_GAME 3
#define CONTROL_CODE_CALL_SEPARATALY 4
#define CONTROL_CODE_SET_GAME_TIME 5
#define CONTROL_CODE_FINISH_THE_GAME 6